# Generated by Django 3.1.7 on 2021-02-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0008_auto_20210226_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billNo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products_order', to='bakery.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
