# Generated by Django 3.1.7 on 2021-02-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0010_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='products_details',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='ingredient_details',
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
